<?php

namespace Proxies\__CG__\Quiz\QzBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Questionnaire extends \Quiz\QzBundle\Entity\Questionnaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'id', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'languageId', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'description', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'welcomeMessage', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'attachement', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'isGenerated', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'type', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'confirmationSms', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'finalMessage', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'name');
        }

        return array('__isInitialized__', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'id', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'languageId', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'description', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'welcomeMessage', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'attachement', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'isGenerated', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'type', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'confirmationSms', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'finalMessage', '' . "\0" . 'Quiz\\QzBundle\\Entity\\Questionnaire' . "\0" . 'name');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Questionnaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguageId($languageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguageId', array($languageId));

        return parent::setLanguageId($languageId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguageId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguageId', array());

        return parent::getLanguageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setWelcomeMessage($welcomeMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWelcomeMessage', array($welcomeMessage));

        return parent::setWelcomeMessage($welcomeMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getWelcomeMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWelcomeMessage', array());

        return parent::getWelcomeMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachement($attachement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachement', array($attachement));

        return parent::setAttachement($attachement);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachement', array());

        return parent::getAttachement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGenerated($isGenerated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGenerated', array($isGenerated));

        return parent::setIsGenerated($isGenerated);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGenerated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGenerated', array());

        return parent::getIsGenerated();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationSms($confirmationSms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationSms', array($confirmationSms));

        return parent::setConfirmationSms($confirmationSms);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationSms', array());

        return parent::getConfirmationSms();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalMessage($finalMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalMessage', array($finalMessage));

        return parent::setFinalMessage($finalMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalMessage', array());

        return parent::getFinalMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

}
