<?php

namespace Quiz\QzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
     public function getQuestionsList($questionnaire_id)
    {
        
        $query = $this->createQueryBuilder('a')
                              ->where('a.questionnaireId = :questionnaire_id')
                              ->setParameter('questionnaire_id', $questionnaire_id)
                              ->getQuery(); 
               
        return $query->getResult();
        
    }
}
