<?php

namespace Quiz\QzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
     public function getResponsesList($question_id)
    {
        
        $query = $this->createQueryBuilder('a')
                              ->where('a.questionId = :question_id')
                              ->setParameter('question_id', $question_id)
                              ->getQuery(); 
               
        return $query->getResult();
        
    }
}
